= Traefik: Reverse Proxy Made Simple

Have you ever felt that your IT super powers were blocked
by repetitive configuration work?
Do you love microservices but hate the sight
of a never-ending routing table?
Does your credo consist of scalability, stability,
traceability, and performance?
Do you believe in a world beyond complex layers of software?
Then you might want to listen to our story
because we are just like you,
and we came up with a practical solution
that might reunite ops and devs alike for a journey to manageable software.

== Generate the Presentation

* You need:
** Docker CE 18.05+ (with local bind-mount capability -
Docker4Mac, Docker4Windows or a local Linux Docker install)
** GNU Make

* Build the slides:
** Clone the repository
** Run the following `make` command:
+
[source,bash]
----
make
----

** Open the resulting file `./dist/index.html`

* "The poor's person live-reload"
** No tools for live-reload here... yet
** "Poor's person" commands:
*** `watch make document`
*** AND `open ./dist/index.html`
